language: php

php:
  - 7
  - 7.1
  - 7.2

cache:
  directories:
    - $HOME/.composer/cache

env:
  - LARAVEL_VERSION="~5.5" TESTBENCH_VERSION="~3.5"

before_script:
  - travis_retry composer update ${COMPOSER_FLAGS} --no-interaction --prefer-dist

script:
  - vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover

notifications:
  email:
    - n.widart@gmail.com
    - josh@joshbrown.me
