language: php

php:
  - 7
  - 5.6

cache:
  directories:
    - $HOME/.composer/cache

env:
  - LARAVEL_VERSION="~5.4" TESTBENCH_VERSION="~3.4"

before_script:
  - travis_retry composer self-update
  - travis_retry composer update ${COMPOSER_FLAGS} --no-interaction --prefer-dist

script:
  - vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover

sudo: false

branches:
  only:
    - 2.0
    - master

notifications:
  email:
    - n.widart@gmail.com
    - josh@joshbrown.me
